### ISSUE TITLE
Ampersand not properly coded in a category

### ISSUE THREAD

**Issue by frankswebstuff** [crwolff/tv_grab_na_zap#1]
First of all, thank you for the great work on this. 
A program was downloaded with the category “Books & Literature”.  The ampersand character was not properly coded with "\&amp;". This is causing an error when importing the program guide into Mythtv and none of the programs for that day get loaded. 

I do not know python programming, but made the following changes to the tv_grab_na_zap file and the ampersand is now coded properly.

--- tv_grab_na_zap	2020-11-18 09:46:05.000000000 -0500
+++ tv_grab_na_zap2	2021-01-23 15:19:16.905797484 -0500
@@ -107,7 +107,9 @@
             #     fClean = re.sub('filter-','',f)
             #     genreList.append(fClean)
             for g in EPgenre:
\-                if g != "Comedy":
\+                gClean = re.sub('&','\&amp;',g)
\+                genreList.append(gClean)
\+            if g != "Comedy":
                     genreList.append(g)
             if 'Movie' in genreList or 'movie' in genreList or 'Movies' in genreList:
                 genreList.insert(0, "Movie / Drama")
@@ -144,7 +146,8 @@
             #     fClean = re.sub('filter-','',f)
             #     genreList.append(fClean)
             for g in EPgenre:
\-                genreList.append(g)
\+                gClean = re.sub('&','\&amp;',g)
\+                genreList.append(gClean)
             if 'Movie' in genreList or 'movie' in genreList or 'Movies' in genreList:
                 genreList = ["Movie / Drama"]
             elif 'News' in genreList:
@@ -172,7 +175,8 @@
             #     fClean = re.sub('filter-','',f)
             #     genreList.append(fClean)
             for g in EPgenre:
\-                genreList.append(g)
\+                gClean = re.sub('&','\&amp;',g)
\+                genreList.append(gClean)
         if 'Movie' in genreList:
             genreList.remove('Movie')
             genreList.insert(0, 'Movie')

**Comment by crwolff** [comment]
Added '&' -> '&amp;' encoding to encwrite(...genre...).
